services:

  db:
    image: mysql:latest
    container_name: db_wordpress
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - db
    container_name: wordpress
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - wordpress-network
    
  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin_wordpress
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8081:80
    env_file: .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    networks:
      - wordpress-network
networks:
  wordpress-network:
    driver: bridge
volumes:
   db:

